QTD-4: Fazer a tela inicial
InfoAlto/Qtanda-site pull request #14
Opened 2023-12-01 04:34 UTC by rScherpel

## Descreva suas mudanças
Fiz a tela de login e criei a pagina de senha esquecida, alem de alguns ajustes no codigo no geral
## Check list
- [x ] Eu fiz o code review do meu código
- [x ] Segui as melhores práticas para garantir a qualidade do código

&nbsp
## Adicione aqui se ficou alguma pendência (geralmente é a área da terra sem lei)

2023-12-01 15:32 UTC, InfoAlto commented on src/main.tsx
> +    </Router>
Cara, vi aqui que fez o esquema antigo no Router
Acaba sendo uma parada deprecated no React 18

Vou deixar como sugestão de melhoria, mas sem problema em seguirmos no modelo antigo

2023-12-01 15:40 UTC, InfoAlto requested changes

2023-12-01 15:40 UTC, InfoAlto commented on src/pages/Login/syle.css
> +  display: flex;
Eu sou meio contra de estilizar baseado em ids
Toda vez que criamos um id no html, por baixo dos panos, ele atribui uma variável a cada elemento

Basicamente, criamos variáveis paenas para estilizar elementos.
O que acha de trocarmos para classes?

Outro ponto:
Vi que estilizou títulos e tudo mais por aqui. O que acha de estilizar esses itens no index.css?
daí conseguimos reutilizar essas classes

2023-12-01 15:45 UTC, InfoAlto commented on src/pages/Login/syle.css
> +  display: flex;
victor aqui rs

2023-12-01 19:19 UTC, rScherpel commented on src/main.tsx
> +    </Router>
cara nesse quesito ai pode ser o que você achar melhor

2023-12-01 19:20 UTC, rScherpel commented on src/pages/Login/syle.css
> +  display: flex;
eu acho bom tambem ia ate falar pra gente usar algo parecido para ter estilos globais, como os estilos eram meio que únicos para cada item eu achei melhor fazer por id, mas sempre q pode ser compartilhado eu uso class

2023-12-02 18:10 UTC, InfoAlto approved these changes

2023-12-02 18:11 UTC, victorfjansen approved these changes

2023-12-07 19:20 UTC, closed without merging