feat(basic-datails): adicionado campos de entrada usando useState
InfoAlto/Qtanda-site pull request #16
Opened 2023-12-09 20:25 UTC by andre-neiva

Implementado o hook useState do React para gerenciar o estado dos campos de entrada do formulário em BasicDetails.tsx. Cada campo de entrada, incluindo email, CNPJ, senha, nome completo, confirmação de senha, CPF e confirmação, agora tem seu próprio estado. Quando o valor de um campo de entrada muda, o estado correspondente é atualizado com o novo valor

2023-12-14 02:34 UTC, victorfjansen commented
Opa, @andre-neiva , o build está quebrando
pode verificar?

2023-12-14 02:56 UTC, victorfjansen requested changes

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/BasicDetails.tsx
> +  };
opa, pode tipar o retorno da função? e também tipar o "password"

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/BasicDetails.tsx
> +  };
(booleano)

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/BasicDetails.tsx
> +  };
opa, pode tipar o valor de "e"?
Essa condicional não é necessária.

```ts
const isPasswordStrong = !isPasswordStrong(e?.target?.value);
setWeakPassword(isPasswordStrong);
```

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/BasicDetails.tsx
> +  };
adicionar operador elvis também

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/BasicDetails.tsx
> +  };
Mesmo caso, não é necessária a condicional:

```ts
const passwordHasChanged = password && e?.target?.value !== password;
setPasswordMismatch(passwordHasChanged);
```

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/BasicDetails.tsx
> +  };
usar elvis operator (null safety)

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/BasicDetails.tsx
> +  };
tipar o "e" e colocar retorno da função

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/BasicDetails.tsx
> +    <div className="details-container">
aqui pode ser uma section

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/BasicDetails.tsx
> +            onChange={(e) => setFullName(e.target.value)}
verificar possibilidade de usar nullsafety (elvis)

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/BasicDetails.tsx
> +          {passwordMismatch && <span className="password-mismatch">As senhas não são iguais</span>}
verificar possibilidade de uso da tag "p"
manter semântica

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/BasicDetails.tsx
> +            onChange={(e) => setEmail(e.target.value)}
usar null safety (elvis)

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/BasicDetails.tsx
> +            onChange={(e) => setCnpj(e.target.value)}
usar null safety (elvis)

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/BasicDetails.tsx
> +            onChange={(e) => setCpf(e.target.value)}
usar null safety (elvis)

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/BasicDetails.tsx
> +          onChange={(e) => setConfirmation(e.target.checked)}
usar null safety (elvis)

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/RegistrationForms.tsx
> +    const { name, value } = e.target;
usar null safety (elvis)

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/RegistrationForms.tsx
> +        <input type="text" name="username" value={formData.username} onChange={handleChange} />
usar null safety (elvis)

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/RegistrationForms.tsx
> +    const { name, value } = e.target;
adicionar retorno da função (void)

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/RegistrationForms.tsx
> +        <input type="password" name="password" value={formData.password} onChange={handleChange} />
usar nullsafety (elvis)

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/RegistrationForms.tsx
> +        <input type="password" name="confirmPassword" value={formData.confirmPassword} onChange={handleChange} />
usar null safety (elvis)

2023-12-14 02:56 UTC, victorfjansen commented on src/pages/SignUp/components/SignUpStepper/components/BasicDetails/style.css
> +    align-items: center;
as cores (hexadeciamais) repetidas desse arquivo poderiam estar em variáveis 

```css
:root {
--bg-color: #000000;
}

.someClass {
  background-color: var(--bg-color);
}
```

2023-12-14 23:30 UTC, victorfjansen commented
@andre-neiva , conflitos da develop

2023-12-14 23:31 UTC, victorfjansen approved these changes

2023-12-14 23:32 UTC, victorfjansen commented
sugestão: fazer squash dos commits e manter em 1 só

2023-12-19 21:07 UTC, rScherpel approved these changes

2023-12-19 21:08 UTC, merged